apiVersion: v1
kind: Service
metadata:
    name: skmsg-metrics-service
spec:
    selector:
        app: skmsg-metrics
    ports:
      - protocol: TCP
        port: 5001
        targetPort: metrics
    type: ClusterIP
